import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DESIGN = path.join(ROOT, 'design');
const GLYPHMAP = 'node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/glyphmaps/MaterialCommunityIcons.json';
const ICON_FONT = '../node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/MaterialCommunityIcons.ttf';
const HEADER = '/* Generated by scripts/design-tokens.mjs; do not edit. */';
const OUTPUTS = ['mobile-tokens.css', 'extension-tokens.css', 'mobile-icons.css'];

const read = (file) => fs.readFileSync(path.join(ROOT, file), 'utf8');
const kebab = (name) => name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
const px = (value) => `${value}px`;

const dataUrl = (source) => `data:text/javascript;base64,${Buffer.from(source, 'utf8').toString('base64')}`;

const bindImports = (file, specifiers) =>
  read(file).replace(/from '([^']+)'/g, (match, specifier) => {
    if (!specifiers[specifier]) throw new Error(`${file}: design-tokens cannot resolve import '${specifier}'`);
    return `from '${specifiers[specifier]}'`;
  });

const loadTheme = async () => {
  const native = dataUrl('export const Appearance = { getColorScheme: () => "light" };');
  const palette = dataUrl(read('src/theme/palette.js'));
  const theme = dataUrl(bindImports('src/theme/theme.js', { 'react-native': native, './palette': palette }));
  const layout = dataUrl(bindImports('src/theme/layout.js', { './theme': theme }));
  const common = dataUrl(bindImports('src/theme/common.theme.js', { './palette': palette }));
  const [paletteModule, themeModule, layoutModule, commonModule] = await Promise.all(
    [palette, theme, layout, common].map((url) => import(url)),
  );
  return { ...paletteModule, ...themeModule, ...layoutModule, ...commonModule };
};

const declare = (entries) => entries.map(([name, value]) => `  --m-${name}: ${value};`).join('\n');

const paletteEntries = (colors) => Object.entries(colors).map(([name, value]) => [kebab(name), value]);

const mobileTokens = async () => {
  const { theme, paletteLight, paletteDark, radius, radiusFull, viewOffset, inputTextHeight, inputPaddingHorizontal, inputPaddingVertical, CommonTheme } =
    await loadTheme();
  const { typography, spacing, animations } = theme;
  const scale = (prefix, values, format = px) => Object.entries(values).map(([name, value]) => [`${prefix}-${name}`, format(value)]);

  const shared = [
    ...scale('font-size', typography.sizes),
    ...scale('line-height', typography.lineHeights),
    ...scale('icon-size', typography.iconSizes),
    ...scale('space', spacing),
    ['radius', px(radius)],
    ['radius-full', px(radiusFull)],
    ['border-width', px(CommonTheme.$borderWidth)],
    ['duration-quick', `${animations.duration.quick}ms`],
    ['duration-standard', `${animations.duration.standard}ms`],
    ['view-offset', px(viewOffset)],
    ['input-text-height', px(inputTextHeight)],
    ['input-padding-x', px(inputPaddingHorizontal)],
    ['input-padding-y', px(inputPaddingVertical)],
    ['logo-font-size', px(CommonTheme.$fontSizeTitle)],
    ['qr-size', px(CommonTheme.$qrSize)],
    ['split-card-height', px(CommonTheme.$splitCardHeight)],
    ['split-card-width', px(CommonTheme.$splitCardWidth)],
    ['scanner-scrim', CommonTheme.$scannerBackgroundOpacity],
  ];

  return [
    HEADER,
    ':root {',
    declare([...paletteEntries(paletteLight), ...shared]),
    '}',
    ':root[data-theme="dark"],',
    '[data-phone-theme="dark"] {',
    declare(paletteEntries(paletteDark)),
    '}',
    '[data-phone-theme="light"] {',
    declare(paletteEntries(paletteLight)),
    '}',
    '',
  ].join('\n');
};

const declarations = (block) => [...block.matchAll(/(--[a-z0-9-]+)\s*:\s*([^;]+);/g)].map(([, name, value]) => [name, value.trim().replace(/\s+/g, ' ')]);

const extensionTokens = () => {
  const css = read('browser-extension/theme.css').replace(/\/\*[\s\S]*?\*\//g, '');
  const light = /:root,\s*:host\s*\{([^}]*)\}/.exec(css);
  const dark = /@media \(prefers-color-scheme: dark\)\s*\{\s*:root,\s*:host\s*\{([^}]*)\}/.exec(css);
  if (!light || !dark) throw new Error('browser-extension/theme.css: expected a light :root, :host block and a dark media block');

  const lightValues = new Map(declarations(light[1]));
  const darkEntries = declarations(dark[1]);
  const lightEntries = darkEntries.map(([name]) => {
    if (!lightValues.has(name)) throw new Error(`browser-extension/theme.css: ${name} is overridden in dark but has no light value`);
    return [name, lightValues.get(name)];
  });
  const render = (entries) => entries.map(([name, value]) => `  ${name}: ${value};`).join('\n');

  return [
    HEADER,
    ':root[data-theme="dark"],',
    '[data-ext-theme="dark"] {',
    render(darkEntries),
    '}',
    ':root[data-theme="light"],',
    '[data-ext-theme="light"] {',
    render(lightEntries),
    '}',
    '',
  ].join('\n');
};

const usedIcons = () => {
  const names = new Set();
  for (const file of fs.readdirSync(DESIGN).filter((name) => name.endsWith('.html'))) {
    const html = fs.readFileSync(path.join(DESIGN, file), 'utf8');
    for (const [, name] of html.matchAll(/(?<![\w-])ic-([a-z0-9-]+)/g)) names.add(name);
  }
  return [...names].sort();
};

const iconRules = () => {
  const glyphs = JSON.parse(read(GLYPHMAP));
  const names = usedIcons();
  const unknown = names.filter((name) => glyphs[name] === undefined);
  if (unknown.length) throw new Error(`design pages use icons missing from MaterialCommunityIcons: ${unknown.join(', ')}`);

  const rules = names.map((name) => `.ic-${name}::before { content: "\\${glyphs[name].toString(16).toUpperCase()}"; }`);
  return [
    HEADER,
    `@font-face { font-family: "MaterialCommunityIcons"; src: url("${ICON_FONT}") format("truetype"); }`,
    ...rules,
    '',
  ].join('\n');
};

export const buildTokenFiles = async () => ({
  'mobile-tokens.css': await mobileTokens(),
  'extension-tokens.css': extensionTokens(),
  'mobile-icons.css': iconRules(),
});

const main = async () => {
  const check = process.argv.includes('--check');
  const files = await buildTokenFiles();
  const stale = [];

  for (const name of OUTPUTS) {
    const target = path.join(DESIGN, name);
    const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
    if (current === files[name]) continue;
    if (check) stale.push(name);
    else fs.writeFileSync(target, files[name]);
  }

  if (check && stale.length) {
    console.error(`design/${stale.join(', design/')} out of date: run node scripts/design-tokens.mjs`);
    process.exit(1);
  }
  if (!check) console.log(`Wrote ${OUTPUTS.map((name) => `design/${name}`).join(', ')}`);
};

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(error.message);
    process.exit(1);
  });
}
